name: Transformar y Subir Summary Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r pipeline/requirements.txt

      - name: Ejecutar notebook
        run: |
          pip install nbconvert pyarrow
          jupyter nbconvert --to notebook --execute pipeline/index.ipynb --output index_executed.ipynb

      - name: Subir a Kaggle
        uses: jaimevalero/push-kaggle-dataset@v3.2
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        with:
          id: "andreschirinos/monitorbolivia"
          title: "Monitoreo en tiempo real del estado de las páginas web de Bolivia."
          subtitle: "Consulta el estado en línea de las páginas web gubernamentales y servicios de Bolivia."
          description: "Columnas: Date - Fecha de la medición. domain - Dominio/subdominio de la página web. time - Tiempo fuera de línea en minutos. type - Tipo de registro (down: fuera de línea, created: inicio de monitoreo, last_updated)."
          files: history/summary.parquet
          is_public: true
